# generated by datamodel-codegen:
#   filename:  agent.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, SecretStr


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the agent's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the agent, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the agent's
    `GET /v1/runtimes`.

    `control` is the trust root, node registry, install-wide
    topology and UI host — exactly one active, plus warm standbys.
    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    **The agent is not in this list**, for the same reason engine
    runtimes are not: it supervises, it is not supervised. Its
    lifecycle belongs to the platform — a systemd unit, a container
    entrypoint — not to a topology entry. `control` *is* in the list
    precisely because the agent on its host supervises it like
    anything else, which is what stops the control root needing a
    second copy of the supervision machinery.

    """

    control = 'control'
    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str | None = Field(
        None,
        description='Message text. Text-only for now; multimodal extensions\ndeferred. **Nullable, and no longer required:** an assistant\nturn that only calls a tool has no text to carry, and the\nalternative — an empty string — would assert the model said\nnothing when in fact it said something that was not text.\n',
    )
    toolCalls: list[dict[str, Any]] | None = Field(
        None,
        description="On an **assistant** message: the tool calls the model made,\nin OpenAI's `{id, type, function: {name, arguments}}` shape.\n\nDeliberately loose here. This is the *shared* schema, so a\ntightly-typed copy would be a third definition of the same\nobject alongside the gateway's and the driver's, and the one\nplace all three must agree is the wire format, which is\nOpenAI's and not ours to restate. The two API documents\ncarry the strict shapes.\n",
    )
    toolCallId: str | None = Field(
        None,
        description='On a **tool** message: which call this is the result of.\n`content` is the result, serialized by the caller.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class ComputeDeviceKind(StrEnum):
    """
    What kind of device this is.

    A named schema rather than an inline enum because an inline one
    generated a bare `Kind` class, which is too generic to sit in a
    module every component imports.

    Note `cpu` is a member, which is why the surrounding schema is
    `ComputeDevice` and not `Accelerator`: a list that includes CPUs
    is a device list. The narrower `HostAccelerator.accelerator` on
    the agent keeps its own name and its own values — it answers
    "which prebuilt engine build fits this machine", not "what can
    this host compute on".

    """

    cuda = 'cuda'
    rocm = 'rocm'
    xpu = 'xpu'
    metal = 'metal'
    cpu = 'cpu'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server` and loads GGUF.
    `vllm` drives upstream `vllm serve` and loads safetensors. MLX
    is a third adapter later. We never ship an engine — every one of
    them is an upstream project we wrap and track.

    The two differ in far more than argv, and that is why readiness
    is per-adapter rather than one shared TCP check:
    `llama-server` answers `/health` while it loads and reports that
    it is loading, whereas vLLM binds its port *before* loading the
    model and refuses connections until the model is in memory — so
    for minutes it is indistinguishable, over the network alone,
    from a process that died. They differ in acquisition too: a
    llama.cpp build is fetched and verified by us, while vLLM is a
    Python package the operator installs themselves. See
    `EngineAcquisition.policy`.

    Lives here rather than on the agent because two components
    reference it: the agent's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'
    vllm = 'vllm'


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08): both are implemented at
    v0.1, and the differences are load-bearing rather than
    cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the agent's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Three of these hold more than a scalar. `path_list` is an
    ordered JSON array of directory paths on the component host —
    the library's model roots are the first and so far only user —
    and the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination.

    `url_list` is the same argument one type over: an ordered JSON
    array of URLs, rendered as an add/remove list of address fields.
    Added at M5 for the control root's standby endpoints, which are
    inherently plural — *"N standbys is a configuration, not a
    mechanism"* — and which have no natural single-value spelling.
    A comma-separated text field would be the same bug report
    `path_list` exists to avoid, and reusing `path_list` for
    addresses would tell every UI to open a directory picker.
    Validation is the field's business rather than the type's; what
    the type promises is a list whose entries are addresses.

    `runtime_name` holds the `name` of a supervised engine runtime,
    and UIs render it as a dropdown sourced from the agent's
    `GET /v1/runtimes`. It exists because `componentKindHint` cannot
    do this job: a runtime is deliberately not a component, so
    `/v1/components` does not list one. What is saved is the
    runtime's *name*, never its URL — the agent assigns the port
    when the operator does not pick one, so a stored URL would
    encode a number the operator never chose and does not own, and
    would be wrong the moment the runtime moved. Its first user is
    the inference-driver's `runtimeName`, which is how a driver
    follows the engine process it fronts.

    `node_name` holds the `name` of an enrolled node, rendered as a
    dropdown sourced from the control root's `GET /v1/nodes`. Same
    reasoning as `runtime_name` one level up: a node is not a
    component either, so `componentKindHint` cannot source it, and
    what is saved is the name rather than a URL because the address
    of a host is topology the control root owns.

    `model_slots` is the gateway's priority-list surface, and the
    one value here that holds objects. An ordered JSON array of
    `{"model": <alias a client asks for>, "targets": [<model id>,
    ...]}`: a request for `model` is served by the drivers serving
    `model` itself, then by the drivers serving each target in
    order, cascading on failure. Targets are **model ids, not driver
    names**, because a model id names a replica set — every driver
    currently serving it, load-balanced — and a driver name would
    name one process. That is why the value reserved since M2 as
    `driver_list` was renamed when M6 defined it: the old name said
    the wrong thing about what goes in the list. A cloud
    subscription is a target like any other, because a
    `claude_code_cli` driver already serves a model id. UIs without
    a structured renderer for it fall back to editing the JSON.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    url_list = 'url_list'
    duration = 'duration'
    runtime_name = 'runtime_name'
    node_name = 'node_name'
    model_slots = 'model_slots'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the agent handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every agent
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the agent. The passphrase is the same one the operator set
    in the wizard. The agent bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the agent at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the agent's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class SpawnConfig(BaseModel):
    configFile: str = Field(
        ...,
        description="Absolute path to the component's own config file. The\nagent passes this to the component via its\nkind-specific env var\n(`EUGENE_PLEXUS_<KIND>_CONFIG_FILE`) at spawn time.\n",
    )
    env: dict[str, str] | None = Field(
        None,
        description='Optional extra environment variables to pass to the\nspawned process. Reserved for advanced operators; the\nwizard never sets this.\n',
    )


class ComponentStatus(StrEnum):
    """
    Current operational state.

    * `starting` — agent has spawned the process but it has
      not yet answered `/healthz`.
    * `running` — process is up and `/healthz` is healthy.
    * `safe_mode` — process is up but launched with
      `SAFE_MODE=1`; will refuse to do useful work until the
      operator fixes its config and clears the safe-mode flag.
    * `exited` — process exited cleanly and the agent is in
      the middle of respawning it (transient state).
    * `crashed` — process has exited non-zero repeatedly and the
      agent has given up auto-restarting it. Operator must
      restart it manually after fixing the cause.
    * `unreachable` — for remote components, the agent can't
      reach the URL. For spawned components this state is not
      used (use `crashed` or `exited` instead).

    """

    starting = 'starting'
    running = 'running'
    safe_mode = 'safe_mode'
    exited = 'exited'
    crashed = 'crashed'
    unreachable = 'unreachable'


class Os(StrEnum):
    windows = 'windows'
    linux = 'linux'
    macos = 'macos'


class Arch(StrEnum):
    x64 = 'x64'
    arm64 = 'arm64'


class EnrollRequest(BaseModel):
    controlUrl: AnyUrl = Field(..., description='The control root to join.')
    token: str = Field(
        ...,
        description='A join token minted at that control root. Single-use and\nshort-lived by design — it is the only credential this node\nhas until enrollment completes.\n',
    )
    name: str | None = Field(
        None,
        description="Requested node name. Defaults to the host's own name, which\nis the answer an operator would have typed anyway.\n",
    )


class RekeyRequest(BaseModel):
    """
    A new signing key, or a new epoch, from the control root. The
    credential is `signature`; see `POST /v1/node/rekey`.

    """

    signingKey: str = Field(
        ...,
        description="The install's service-token signing key, base64. During a\npromotion's announcement this is the key the agent already\nholds.\n",
    )
    signingKeyId: str = Field(
        ..., description="The key's generation, as `Snapshot.signingKeyId` names it."
    )
    epoch: int = Field(
        ...,
        description="The control root's current epoch. The agent refuses a value\nbelow the highest it has recorded.\n",
        ge=0,
    )
    signature: str = Field(
        ...,
        description='Detached Ed25519 signature, base64, by the control root\'s\nidentity key over the **canonical message**: the UTF-8 bytes of\nthe JSON object `{"epoch": <epoch>, "signingKey":\n"<signingKey>", "signingKeyId": "<signingKeyId>"}` with keys\nsorted and no whitespace — `json.dumps(obj, sort_keys=True,\nseparators=(",", ":"))`. Verified against the\n`controlPublicKey` the agent recorded at enrollment. Three\nfields, one serializer, stated here so both sides implement it\nfrom the same sentence.\n',
    )


class UnenrollRequest(BaseModel):
    """
    Optional. The default does the right thing; the field exists for
    the operator who already knows the root is gone and does not want
    to wait for the attempt to time out.

    """

    notifyControl: bool | None = Field(
        True,
        description='Call `DELETE /v1/nodes/{name}` at the control root first, so\nthe install rotates its signing key and stops trusting this\nnode. Set false to skip the attempt entirely — it does not\nchange what happens *here*, only whether the root is told.\n',
    )


class AuthStatus(BaseModel):
    """
    Whether this install has been through first-run setup.

    """

    initialized: bool = Field(
        ...,
        description='True once a passphrase has been set. False means every\nendpoint except this one, `/healthz` and\n`POST /v1/auth/initialize` will refuse.\n',
    )


class AuthInitializeRequest(BaseModel):
    passphrase: SecretStr = Field(
        ...,
        description='The operator passphrase. Hashed with Argon2id and used to\nderive the master key that at-rest secrets are sealed\nunder, so losing it means losing every stored credential —\nthere is no recovery path by design.\n',
        min_length=1,
    )


class ManagedEngine(BaseModel):
    """
    A build this install fetched and owns, as opposed to one found on
    PATH or pointed at by hand. Present only when we installed it.

    """

    version: str = Field(
        ...,
        description='Upstream build identifier - for llama.cpp a `bNNNN` tag, not\na semver. Copied verbatim from the release, because the only\nuseful thing to do with it is compare it to what upstream\nhas.\n',
    )
    binaryPath: str = Field(
        ..., description='Absolute path to the executable inside the managed directory.'
    )
    variant: str = Field(
        ...,
        description='Which asset was chosen, e.g. `win-cuda-13.3-x64`. Recorded\nbecause it is the answer to "why is this slow" often enough\nto be worth surfacing: a host that fell back to a CPU build\nlooks identical from the outside otherwise.\n',
    )
    installedAt: AwareDatetime | None = None
    sizeBytes: int | None = Field(
        None,
        description='On-disk size of this build. A Windows CUDA install is roughly\nhalf a gigabyte unpacked and we retain two, so this is worth\nshowing before someone asks where their disk went.\n',
    )
    previousVersion: str | None = Field(
        None,
        description='The build retained alongside this one, if any. Retention is\ncurrent plus previous: keeping every build is not viable at\nthis size, and keeping only the newest leaves a bad upgrade\nwith no way back.\n',
    )


class Policy(StrEnum):
    """
    Whether this engine is one we install at all. A property of
    the engine, not of this host.

    * `managed` — we fetch, verify and retain builds of it.
      llama.cpp, which ships prebuilt release assets with
      per-asset digests.
    * `manual` — the operator installs it and we discover what
      they installed. vLLM, whose unit of installation is a
      Python environment: an interpreter of a version we do not
      control (specifically 3.12 for the ROCm and Intel wheels),
      several GB per retained copy, three of six targets on a
      non-default package index, Apple silicon served by a
      separate project entirely, and no single digest that
      verifies the result. Decided 2026-09-09.

    Separate from `installable` because the two answer different
    questions and the UI renders them differently.
    `installable: false` under `policy: managed` means *not on
    this host* — there is a build, just not for this one, which
    is Linux + NVIDIA llama.cpp. `policy: manual` means *not by
    us, anywhere*, and the UI owes the operator instructions
    (`manualInstall`) rather than a disabled install button.
    Inferring that difference from a false boolean would be
    guesswork.

    """

    managed = 'managed'
    manual = 'manual'


class ManualInstall(BaseModel):
    """
    Instructions for installing an engine we do not manage, written
    for the host we actually detected.

    This exists so that "we don't install this one" is still an
    answer the operator can act on. A refusal that names the exact
    command is a different product from a refusal that says no —
    and since a `manual` engine's refusal is permanent rather than
    situational, it is the only surface the operator gets.

    """

    command: str | None = Field(
        None,
        description='A copy-pasteable command for the detected platform and\naccelerator, e.g.\n`uv pip install vllm --torch-backend=auto`. Omitted when we\ncannot name one honestly — an unrecognised accelerator, or a\ntarget upstream serves from a separate project — in which\ncase `docsUrl` and `notes` carry it. Never a guess: a\ncommand that does not work is worse than no command, because\nthe operator will believe it.\n',
    )
    docsUrl: str = Field(
        ...,
        description="Upstream's own install page. Required, and deliberately the\none field that always exists: upstream's instructions are\ncorrect for longer than any copy we make of them, and this\nis the value that stays right when our `command` goes stale.\n",
    )
    notes: str | None = Field(
        None,
        description='Constraints the command alone does not convey — a required\nPython version, a non-default package index, that this\ntarget is served by a separate upstream project, or that the\nplatform is unsupported and the way in is a Linux VM.\n',
    )


class Accelerator(StrEnum):
    """
    `metal` is reported on Apple silicon even though there is no
    separate Metal asset - the plain macOS build has it compiled
    in, and saying `none` there would read as "no GPU".

    """

    none = 'none'
    cuda = 'cuda'
    rocm = 'rocm'
    metal = 'metal'
    sycl = 'sycl'


class HostAccelerator(BaseModel):
    """
    What the agent detected about this machine, insofar as it
    decides which engine build to fetch. Not a general hardware
    inventory - the VRAM-and-quant-fit surface that M3 needs belongs
    to the library component, not here.

    """

    os: Os | None = None
    arch: Arch | None = None
    accelerator: Accelerator | None = Field(
        None,
        description='`metal` is reported on Apple silicon even though there is no\nseparate Metal asset - the plain macOS build has it compiled\nin, and saying `none` there would read as "no GPU".\n',
    )
    acceleratorVersion: str | None = Field(
        None,
        description='For CUDA, the highest version the installed driver supports.\nSelection takes the highest published build whose major\nmatches and whose minor is no greater than this; a higher\nmajor is never chosen.\n',
    )


class EngineInstallRequest(BaseModel):
    version: str | None = Field(
        None,
        description='A specific upstream build to install. Omit for the newest.\nPresent so an operator who found a regression can pin the\nbuild that worked, which is the whole reason we record the\nversion rather than just "installed".\n',
    )


class State(StrEnum):
    """
    * `resolving` - asking upstream which build and which asset.
    * `downloading` - fetching. On Windows with CUDA this is two
      assets, the binary and a separate CUDA runtime, and the
      byte counters cover both.
    * `verifying` - comparing the SHA-256 the releases API
      reported for the asset. Upstream publishes no checksum
      file; the digest arrives with the asset metadata, so
      there is no excuse for skipping this.
    * `extracting` - unpacking into a new versioned directory.
    * `done` / `failed` / `cancelled` - terminal, and retained
      until the next install starts.

    """

    resolving = 'resolving'
    downloading = 'downloading'
    verifying = 'verifying'
    extracting = 'extracting'
    done = 'done'
    failed = 'failed'
    cancelled = 'cancelled'


class EngineInstall(BaseModel):
    """
    Progress of one install. Phases are named rather than reduced to
    a percentage because they fail differently and the operator
    needs to know which one they are in: a stall in `downloading` is
    the network, a stall in `extracting` is the disk, and a failure
    in `verifying` is the one that means do not run this.

    """

    engine: EngineKind
    state: State = Field(
        ...,
        description='* `resolving` - asking upstream which build and which asset.\n* `downloading` - fetching. On Windows with CUDA this is two\n  assets, the binary and a separate CUDA runtime, and the\n  byte counters cover both.\n* `verifying` - comparing the SHA-256 the releases API\n  reported for the asset. Upstream publishes no checksum\n  file; the digest arrives with the asset metadata, so\n  there is no excuse for skipping this.\n* `extracting` - unpacking into a new versioned directory.\n* `done` / `failed` / `cancelled` - terminal, and retained\n  until the next install starts.\n',
    )
    version: str | None = Field(
        None, description='The build being installed, once resolved.'
    )
    variant: str | None = None
    bytesDownloaded: int | None = None
    bytesTotal: int | None = Field(
        None,
        description='Total across every asset this install needs. Absent until\n`resolving` finishes.\n',
    )
    message: str | None = Field(
        None, description='What is happening now, for a status line.'
    )
    error: str | None = Field(None, description='Populated when `state: failed`.')
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class Origin(StrEnum):
    """
    Where the binary came from. Discovery precedence is an
    explicit `binary` on the runtime, then `configured`, then
    `managed`, then `PATH`.

    * `managed` — fetched and verified by us. Only ever set for
      an engine with `acquisition.policy: managed`.
    * `configured` — an explicit path the operator set. Two
      sources: a `binary` on one runtime, for someone who builds
      llama.cpp themselves or wants a specific build for one
      model; or an install-wide path in the agent's own
      config, which is how an engine we never manage becomes
      discoverable at all. Without the second, an operator with
      a perfectly good vLLM venv would read as unavailable
      unless they put it on `PATH` or repeated the path on every
      runtime.
    * `path` — found on `PATH`.

    """

    managed = 'managed'
    configured = 'configured'
    path = 'path'


class FrameworkAccelerator(StrEnum):
    """
    What a Python engine's installed framework was *built for*, read
    from its build tag rather than from the host.

    Deliberately a separate schema from `HostAccelerator.accelerator`
    rather than a shared one, because the two say different things
    and carry different values. That one reports what the *machine*
    has; this one reports what the *wheel* has. A CUDA box running a
    CPU-only PyTorch is a real and quiet failure — everything looks
    installed and inference is orders of magnitude slower — and it
    is visible only as the disagreement between these two fields.

    `unknown` when the build tag does not parse. Honest, and better
    than reporting `none`, which would read as a definite claim that
    there is no acceleration.

    """

    none = 'none'
    cuda = 'cuda'
    rocm = 'rocm'
    xpu = 'xpu'
    metal = 'metal'
    unknown = 'unknown'


class RuntimeSpec(BaseModel):
    """
    Declarative half of a Runtime — what the operator asked for.
    Used for create and update bodies; observed fields are
    server-owned and excluded.

    Note what is *not* here: a command line. The operator declares
    intent (this engine, this model, these flags) and the adapter
    builds the argv. Letting a topology entry carry raw argv would
    make every engine "supported" while making none of them
    knowable — no readiness probe, no flag validation, no version
    story. The resolved argv is reported back on `Runtime.argv` for
    debugging, which is the half of raw-argv access that is
    genuinely useful.

    """

    name: str = Field(
        ...,
        description="Operator-supplied label, unique per install. Referenced by\nan inference-driver's config to say which runtime it fronts.\n",
        min_length=1,
    )
    engine: EngineKind
    modelPath: str = Field(
        ...,
        description="Absolute path to the model on this host — a `.gguf` file, or\na directory for multi-file formats. **The operator's own\npath, in the operator's own layout.** We never relocate,\nrename, or hash-address a model file; a runtime points at\nwhere the user put it.\n\nFor a sharded GGUF this is the *first* shard\n(`…-00001-of-0000N.gguf`), which is what the engine expects.\nWhen a runtime is created from the library, this is the\n`path` off a `LibraryModel` and the `flags` are a\n`ModelProfile` — but nothing here depends on the library\nexisting, and a hand-written runtime is still a runtime.\n",
    )
    modelAlias: str | None = Field(
        None,
        description="The model id this runtime serves under, and therefore what a\nclient asks the gateway for. Defaults to the model\nfilename with its extension stripped — plainly-named files\nmean the obvious name is already the right one, so this is\nan override, not a requirement.\n\n**The resolved value is always passed to the engine\nexplicitly, never left to the engine's own default.** vLLM's\ndefault served name is the `--model` argument verbatim, and\nwe launch models by absolute path because the user's files\nstay theirs — so leaving it unset would publish\n`/home/you/models/Qwen3-8B` as an OpenAI model id. That\nleaks the operator's directory layout to every API client\nand, worse, makes the routing key differ per host for the\nsame model, which breaks both multi-host placement and any\nfailover priority list that names a model. llama.cpp derives\nits default from the filename and would have been fine,\nwhich is exactly why this was invisible until a second\nengine existed.\n",
    )
    host: str | None = Field(
        '127.0.0.1',
        description="Address the engine binds. Defaults to loopback: an engine\nhas no auth of its own, so it must not be exposed directly.\nReaching a model from another machine is the gateway's job,\nand the gateway has auth.\n",
    )
    port: int | None = Field(
        None,
        description='Port the engine binds. Assigned from an ephemeral range when\nomitted — with N runtimes the operator should not have to\nhand out port numbers.\n',
        ge=1,
        le=65535,
    )
    autoStart: bool | None = Field(
        True,
        description='Whether the agent spawns this runtime at startup and\nrespawns it on exit. False leaves it declared but\n`stopped`, which is how a rarely-used large model stays\nconfigured without holding VRAM.\n',
    )
    autoDriver: bool | None = Field(
        True,
        description='Whether the agent declares and supervises a companion\n`inference-driver` that follows this runtime by name, so\nthe model is routable the moment the engine is ready. The\ncompanion is `<name>-driver`; `Runtime.driver` reports it.\nSet false to front the runtime by hand — one hand-tuned\ndriver pointed at an engine is still a supported shape, it\nis just no longer the only one. Decided 2026-09-10 over a\ndeclared pool: one driver per backend is the rule the\ncontract has stated since M0, a runtime is a backend, and a\npool would need allocation state and give drivers names\nthat mean a different model every hour.\n',
    )
    idleUnloadSeconds: int | None = Field(
        None,
        description="Stop the engine after this many seconds with no request for\nits model through the gateway, releasing its GPU memory.\nAbsent or 0 means never, which is every existing\ndeclaration's behaviour unchanged.\n\n**The gateway decides; this agent executes.** Only the\ngateway sees demand, so it tracks the last request per\nruntime and calls `POST .../stop` with `reason: idle` when\nthis expires. A runtime with a request in flight is never\nstopped. Setting this also **opts the runtime into\neviction**: when a `startOnDemand` model will not fit, the\ngateway may stop the most-idle runtimes that carry a timeout\nto make room. A model that must stay resident sets none.\n",
        ge=0,
    )
    startOnDemand: bool | None = Field(
        False,
        description="Start this runtime when a request arrives for its model and\nit is `stopped`. The gateway calls `POST .../start`, waits\nfor `ready` (bounded by its `swapWaitSeconds`), and serves\nthe request; the response says it did (`swapped_in`). With\n`autoStart: false` and `idleUnloadSeconds` set, this is\nllama-swap's model: declare five, load none, serve whichever\nis asked for, unload it when it goes quiet — several at\nonce when they fit.\n\nFalse by default so that a hand-pressed Stop stays stopped.\n",
    )
    flags: dict[str, Any] | None = Field(
        None,
        description='Curated engine flags, keyed by the field names in the\nadapter\'s `flagSchema`. Validated on write: an unknown key\nis a 400, never a silent drop.\n\nThis is the per-model settings surface — the reason\n"tweaking llama.cpp settings for every different model" is a\ncomplaint we answer. Values here are engine *launch* flags;\nsampling parameters that ride on each request are the\ngateway\'s, not these.\n',
    )
    extraArgs: list[str] | None = Field(
        None,
        description='Verbatim extra arguments, appended after everything the\nadapter generated. The escape hatch for the long tail of\nflags a curated surface will always miss.\n\nUnvalidated by definition, so the UI must present it as the\nadvanced option it is: a bad value here surfaces as an\nengine that refuses to start, and the resolved `argv` plus\nthe captured engine output are how it gets diagnosed.\n',
    )
    env: dict[str, str] | None = Field(
        None,
        description='Extra environment variables for the engine process. Needed\nmore often than for a component — accelerator selection\n(`CUDA_VISIBLE_DEVICES`, `HIP_VISIBLE_DEVICES`) is how a\nruntime is pinned to one GPU, which is what makes two\nreplicas on two cards possible.\n',
    )
    workingDirectory: str | None = Field(
        None,
        description="Working directory for the engine process. Defaults to the\nbinary's own directory, which is what prebuilt llama.cpp\nreleases need to find their bundled shared libraries.\n",
    )
    binary: str | None = Field(
        None,
        description='Override the binary for this one runtime, ignoring whatever\nthe adapter discovered. For running one model on a custom\nbuild without disturbing the rest of the install.\n',
    )


class RuntimeStatus(StrEnum):
    """
    Operational state of an engine process. Distinct from
    `ComponentStatus`: an engine has no safe mode (nothing to
    recover a config from), and it has a model-load phase that a
    component does not.

    These are defined by what they *mean*, not by how any one engine
    reports them. That distinction is load-bearing, because the two
    engines report the load phase in opposite ways — see `loading`.

    * `starting` — spawned, and we have no information yet. Not "the
      probe failed": the honest gap between spawning a process and
      learning anything about it.
    * `loading` — the engine is alive and working, and is not
      servable yet. Worth its own state rather than folding into
      `starting`: a large quant off a spinning disk can sit here for
      minutes, and an operator staring at a dashboard needs to know
      the difference between "working on it" and "wedged".

      How it is *observed* is per-engine, and this is most of why
      readiness is per-adapter rather than a shared TCP check.
      `llama-server` says so itself, answering `/health` with 503
      and a loading status. **vLLM does the opposite:** it binds its
      port before loading the model and does not answer at all until
      the model is in memory, so for minutes it is
      indistinguishable — over the network alone — from a process
      that died.

      Hence the rule: for an engine that does not answer while
      loading, *the process being alive while nothing answers* **is**
      `loading`. There is nothing else it could be. That inference
      needs the process handle, which the supervisor has and a
      network probe does not, and it is why lifecycle adapters live
      here rather than in the driver. An engine like that also needs
      a per-adapter startup budget to keep "working on it" separable
      from "wedged"; vLLM's is minutes, because CUDA graph capture
      and compilation dominate it.
    * `ready` — model loaded and serving. The only state in which
      the gateway will route to it.
    * `stopped` — deliberately stopped, or declared with
      `autoStart: false`. Not an error; the respawn loop is
      suppressed.
    * `exited` — exited cleanly and is being respawned (transient).
    * `crashed` — exited non-zero repeatedly and the agent has
      given up. `lastError` and the captured engine output say why;
      `POST .../restart` retries.

    """

    starting = 'starting'
    loading = 'loading'
    ready = 'ready'
    stopped = 'stopped'
    exited = 'exited'
    crashed = 'crashed'


class RuntimeCapabilities(BaseModel):
    """
    What the running engine reports about itself, read back after it
    becomes ready rather than inferred from the declaration. The
    gateway keys routing decisions off these; the UI displays them.

    """

    contextLength: int | None = Field(
        None,
        description='Effective context window of the loaded model, as the engine\nresolved it — which is not necessarily what was asked for.\nA requested context larger than the model or the available\nmemory gets clamped by the engine, and the clamped value is\nthe true one.\n',
        ge=0,
    )
    parallelSlots: int | None = Field(
        None,
        description='Concurrent requests this runtime can serve. The unit of\ncapacity the gateway divides work across, so a single\nruntime with several slots and several runtimes with one\neach are the same kind of thing to the layer above.\n',
        ge=1,
    )
    embeddings: bool | None = Field(
        None, description='Whether this runtime was started in embedding mode.'
    )
    multimodal: bool | None = Field(
        None, description='Whether a projector was loaded alongside the model.'
    )


class StopReason(StrEnum):
    """
    * `operator` — an explicit stop, from the UI or the API.
    * `idle` — the gateway unloaded it after `idleUnloadSeconds`
      passed with no request for its model. It comes back on the
      next request if `startOnDemand` is set.
    * `autoStart` — declared with `autoStart: false` and never
      started in this agent's lifetime.

    A reason beside `status: stopped` rather than three new members
    of `RuntimeStatus`, because the state is the same state — the
    process is not running and the respawn loop is suppressed — and
    only the cause differs.

    """

    operator = 'operator'
    idle = 'idle'
    autoStart = 'autoStart'


class AdmissionDecision(StrEnum):
    """
    Refuse, never queue (decided 2026-09-10). A refusal carries its
    numbers and is overridable with `force`; the on-demand path is
    how a model that does not fit right now gets loaded when it is
    actually asked for.

    """

    admit = 'admit'
    refuse = 'refuse'


class AdmissionFit(StrEnum):
    """
    The same four words the library's guidance uses, plus `unknown`,
    mapped onto a decision by what the spec asked for. `fits` admits.
    `tight` — inside total memory but not free memory — and `split`
    — needs host memory too — refuse a full-offload launch and admit
    one whose `gpuLayers` is set below full, because then the
    operator chose partial offload. `no` refuses. `unknown` admits
    with a warning: a verdict from a budget that could not be
    measured is worse than none.

    """

    fits = 'fits'
    tight = 'tight'
    split = 'split'
    no = 'no'
    unknown = 'unknown'


class AdmissionBasis(StrEnum):
    """
    * `metadata` — the library computed required bytes from the
      model's real metadata at the requested context. Present when
      a `library` component is in this agent's topology and
      answered.
    * `file_size` — the model file's size plus a fixed allowance.
      What an agent with no library reachable can measure on its
      own, said out loud rather than dressed up.

    """

    metadata = 'metadata'
    file_size = 'file_size'


class AdmissionBlocker(BaseModel):
    name: str = Field(..., description='A runtime holding memory on the device.')
    status: RuntimeStatus | None = None
    idleUnloadSeconds: int | None = Field(
        None,
        description='Its declared idle timeout, when it has one. Only a runtime\nwith one is ever evicted by the gateway; the rest are here\nso the operator knows what is holding the memory.\n',
    )
    evictable: bool | None = Field(
        None,
        description='Whether the gateway may stop this runtime to make room —\ntrue exactly when it declared `idleUnloadSeconds`.\n',
    )


class Component(BaseModel):
    """
    Combined declarative + operational view of one supervised
    component. The declarative half (`name`, `kind`, `url`,
    `spawn`, `safeMode`) is what's persisted to `agent.yaml`.
    The operational half (`status`, `lastRestart`, `lastError`,
    `pid`) is observed at runtime and not persisted.

    """

    name: str = Field(
        ...,
        description="Operator-supplied label, also used in the gateway's `drivers` list.",
    )
    kind: ComponentKind
    url: AnyUrl = Field(
        ...,
        description='Canonical address. For spawned components the agent\nparses the port out of this URL and passes it via env var\n(`EUGENE_PLEXUS_<KIND>_BIND_PORT`); for remote components\nthis is what the agent probes.\n',
    )
    advertiseUrl: AnyUrl | None = Field(
        None,
        description="Where a **peer on another host** reaches this component: the\nagent's advertise host with this component's port. Derived,\nnever declared, and present only for a component this agent\nspawns on an agent that has an advertise address\n(`NodeIdentity.advertiseUrl`). `url` keeps its one meaning —\nwhat the agent binds and probes — and the gateway prefers this\nfield and falls back to `url`, which is the whole of what makes\na companion driver on one host routable from a gateway on\nanother. Absent on a single-host install, where the two would\nsay the same thing.\n",
    )
    spawn: SpawnConfig | None = Field(
        None,
        description="Present iff this component runs locally under agent\nsupervision. Absence means it's remote (the agent only\nmonitors reachability).\n",
    )
    safeMode: bool | None = Field(
        False,
        description='When true the agent launches the spawned component with\n`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`, telling it to ignore its\nown config file and boot from defaults. Used to recover\nfrom a config that breaks startup. Ignored for remote\ncomponents.\n',
    )
    status: ComponentStatus
    pid: int | None = Field(
        None,
        description='Operating-system process id. Set only for spawned, currently-running components.',
    )
    lastRestart: AwareDatetime | None = Field(
        None, description='When the agent last started or restarted this component.'
    )
    lastError: str | None = Field(
        None,
        description="Most recent error observed for this component. Reset to null\non successful restart. Useful for surfacing why a component\nkeeps crashing in the UI's Components tab.\n",
    )


class ComputeDevice(BaseModel):
    """
    One compute device on one host, as that host's agent detected it.

    Shared because it appears on both sides of a join: an agent
    reports its own devices on `GET /v1/node`, and the control root
    aggregates them into `Node.devices` — the cross-host
    inventory M3 deferred with the note that *"building a real
    inventory is topology work"*. Two copies of this shape would be
    two definitions of one fact, and the copy would be the one that
    went stale.

    Deliberately **not** the same thing as the agent's
    `HostAccelerator`, which answers a narrower question — "which
    prebuilt engine build should we fetch for this machine" — and
    describes a host in the singular. This is a device *list*,
    because a host with two cards is the case that makes replicas of
    one model possible.

    """

    kind: ComputeDeviceKind
    name: str | None = Field(
        None,
        description='Device name as the vendor reports it, e.g. `NVIDIA GeForce RTX 5090`.',
    )
    index: int | None = Field(
        None,
        description="Device ordinal on its own host — what `CUDA_VISIBLE_DEVICES`\nor `HIP_VISIBLE_DEVICES` in a runtime's `env` selects to pin\nthat runtime to one card.\n",
        ge=0,
    )
    memoryTotalBytes: int | None = None
    memoryFreeBytes: int | None = Field(
        None,
        description='Free decides whether a model fits, not total — M3 measured\n2.9 GiB of a 32 GiB card already held on an idle desktop.\nBoth are reported so the difference is visible rather than\nsurprising.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the agent's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class ComponentEntry(BaseModel):
    """
    Declarative half of a Component, used for create / update
    request bodies. Status fields are server-owned and excluded.

    """

    name: str
    kind: ComponentKind
    url: AnyUrl
    spawn: SpawnConfig | None = None
    safeMode: bool | None = False


class NodeIdentity(BaseModel):
    """
    What this agent knows about its own host and its own place in an
    install. The install-wide `Node` view lives on the control root;
    this is the half only the host itself can answer.

    """

    enrolled: bool = Field(
        ...,
        description='False on a fresh agent, and not an error state — supervision\nworks without a trust relationship, which is what lets the\nagent on the control host boot first and start the control\nroot.\n',
    )
    name: str | None = Field(
        None, description="This node's name in the install. Absent until enrolled."
    )
    publicKey: str | None = Field(
        None,
        description="This node's identity public key. The private half never\nleaves the host; a secret sealed to this key is readable here\nand by the control root's recovery recipient, and nowhere\nelse.\n",
    )
    controlUrl: AnyUrl | None = Field(
        None, description='The control root this node answers to.'
    )
    epoch: int | None = Field(
        None,
        description='Highest control-root epoch this agent has acknowledged. **It\nrefuses any root presenting a lower one**, which fences a\nsuperseded control root without an election, without quorum,\nand without agreeing with any other agent.\n',
        ge=0,
    )
    advertiseUrl: AnyUrl | None = Field(
        None,
        description="Where other hosts reach this agent — the `advertiseUrl` config\nfield, or the value derived at enrollment when none was set.\nWhat the control root holds as this node's `Node.url`.\n",
    )
    signingKeyId: str | None = Field(
        None,
        description='The generation of the install signing key this agent holds,\nas the control root named it. During a rotation, the answer\nto "which host is stale" from the host itself.\n',
    )
    controlPublicKey: str | None = Field(
        None,
        description="The identity public key of the control root this agent\nenrolled with, recorded then and checked against every\n`POST /v1/node/rekey` since. A dashboard can compare it with\nthe root's own `Snapshot.controlPublicKey`.\n",
    )
    signingPublicKey: str | None = Field(
        None,
        description="This node's **Ed25519** identity public key — the one it\nsigns `PATCH /v1/nodes/{name}` with, recorded at the control\nroot as `Node.signingPublicKey`.\n\nSeparate from `publicKey`, which is X25519 and exists to have\nsecrets sealed *to* it. One key cannot do both jobs: sealing\nis Diffie-Hellman and signing is Ed25519, and deriving one\nfrom the other only runs in the direction we do not have.\n\nAbsent on a node enrolled before this key existed, which is\nalso why its re-advertisements are refused — see\n`PATCH /v1/nodes/{name}` in `control.yaml`.\n",
    )
    advertiseSequence: int | None = Field(
        None,
        description='How many address announcements this node has made since it\nenrolled. Strictly increasing, persisted here and mirrored at\nthe control root, so a replayed announcement cannot move a\nnode back to an address it used to have.\n',
        ge=0,
    )
    os: Os | None = None
    arch: Arch | None = None
    devices: list[ComputeDevice] | None = Field(
        None,
        description='What this host can compute on, detected locally. The control\nroot aggregates these into the cross-host inventory M3\ndeferred; detection stays here because only the host can do\nit.\n',
    )
    agentVersion: str | None = None


class UnenrollResult(BaseModel):
    identity: NodeIdentity
    controlNotified: bool = Field(
        ...,
        description='Whether the control root accepted the revocation. **False is\nnot a failure of this call** — the node has left either way.\nIt means the install still lists this node and still trusts\nthe key it just discarded, and an operator owes it a\n`DELETE /v1/nodes/{name}`.\n',
    )
    previousName: str | None = Field(
        None, description='The name this node had in the install it just left.'
    )
    previousControlUrl: AnyUrl | None = Field(
        None, description='The control root it answered to.'
    )
    detail: str | None = Field(
        None,
        description='Why the root was not told, when it was not. Present exactly\nwhen `controlNotified` is false and something was attempted.\n',
    )


class EngineAcquisition(BaseModel):
    """
    Whether this host can be given a build of this engine, and which
    one. Answers the question before the operator commits to a
    several-hundred-megabyte download.

    """

    policy: Policy | None = Field(
        None,
        description='Whether this engine is one we install at all. A property of\nthe engine, not of this host.\n\n* `managed` — we fetch, verify and retain builds of it.\n  llama.cpp, which ships prebuilt release assets with\n  per-asset digests.\n* `manual` — the operator installs it and we discover what\n  they installed. vLLM, whose unit of installation is a\n  Python environment: an interpreter of a version we do not\n  control (specifically 3.12 for the ROCm and Intel wheels),\n  several GB per retained copy, three of six targets on a\n  non-default package index, Apple silicon served by a\n  separate project entirely, and no single digest that\n  verifies the result. Decided 2026-09-09.\n\nSeparate from `installable` because the two answer different\nquestions and the UI renders them differently.\n`installable: false` under `policy: managed` means *not on\nthis host* — there is a build, just not for this one, which\nis Linux + NVIDIA llama.cpp. `policy: manual` means *not by\nus, anywhere*, and the UI owes the operator instructions\n(`manualInstall`) rather than a disabled install button.\nInferring that difference from a false boolean would be\nguesswork.\n',
    )
    installable: bool = Field(
        ...,
        description='False means we will not be installing this engine here, and\n`reason` says why. This is a real outcome, not an error, and\nit arises two ways. Under `policy: managed` no published\nasset fits this host — upstream publishes no CUDA build for\nLinux, so a Linux box with an NVIDIA GPU cannot be served\nautomatically and is told so rather than quietly handed a\nslower Vulkan build it never asked for. Under\n`policy: manual` it is always false, on every host, by\ndecision.\n',
    )
    variant: str | None = Field(
        None, description='The asset variant that would be fetched, when installable.'
    )
    reason: str | None = Field(
        None,
        description='Why not, when `installable: false`. Written for the operator,\nnaming the way forward - build from source, use a container,\nor point `binary` at an existing build. For a\n`policy: manual` engine the way forward is an install the\noperator performs, and `manualInstall` carries the command\nitself.\n',
    )
    manualInstall: ManualInstall | None = Field(
        None,
        description='How the operator installs this engine themselves. Present\nfor `policy: manual`, and the reason driving an engine is a\nsupported path rather than a shrug.\n',
    )
    detected: HostAccelerator | None = None
    latestVersion: str | None = Field(
        None, description='Newest upstream build we know of.'
    )
    latestPublishedAt: AwareDatetime | None = Field(
        None,
        description='When that build shipped. Deliberately the age of the newest\nbuild rather than a count of builds behind: llama.cpp\npublishes several a day, so "1,021 builds behind" is noise\nand "your build is three weeks old" is information.\n',
    )
    checkedAt: AwareDatetime | None = Field(
        None,
        description='When we last asked upstream. Checked at most daily and never\non the request path; a failed check leaves this stale rather\nthan raising anything.\n',
    )


class PythonEngine(BaseModel):
    """
    The environment a Python-package engine was found in.

    This is the `ManagedEngine.variant` idea applied to an engine
    whose build is a property of its environment rather than of a
    filename: recorded because it is the answer to "why is this
    slow" often enough to be worth surfacing. A venv holding a
    CPU-only PyTorch looks identical from the outside to one holding
    a CUDA build and runs orders of magnitude slower, and nothing
    else on this descriptor would ever say so.

    """

    interpreter: str = Field(
        ...,
        description="Absolute path to the interpreter behind the engine's console\nscript. The script's own shebang binds it, so nothing needs\nactivating and the argv stays a plain executable invocation —\nbut the interpreter is what identifies *which* install is in\nuse when an operator keeps more than one.\n",
    )
    pythonVersion: str | None = Field(
        None,
        description='e.g. `3.12.8`. Surfaced rather than merely logged because it\nis sometimes the whole problem and is not fixable from here:\nupstream publishes the ROCm and Intel wheels for 3.12 only,\nso an operator on 3.13 has an unusable environment and the\nonly useful thing we can do is show them the number.\n',
    )
    packageVersion: str | None = Field(
        None,
        description="The engine package's own version, from the installed\ndistribution's metadata. Mirrors `EngineDescriptor.version`\nand is here so the environment reads as a self-contained\nrecord.\n",
    )
    torchVersion: str | None = Field(
        None,
        description='The installed PyTorch version *including its build tag* —\ne.g. `2.9.0+cu129`. The tag is the load-bearing half: it is\nwhat distinguishes a CUDA build from a CPU-only one, which\nis the single most useful fact about an environment that is\nserving slowly.\n',
    )
    accelerator: FrameworkAccelerator | None = None


class Runtime(BaseModel):
    """
    Combined declarative + operational view of one engine process.
    The declarative half is `RuntimeSpec` and is persisted; the
    operational half is observed and is not.

    """

    name: str
    engine: EngineKind
    modelPath: str
    modelAlias: str | None = Field(
        None,
        description='Resolved alias — the declared value, or the derived filename.',
    )
    host: str | None = None
    port: int | None = Field(
        None, description='Resolved port, including one assigned by the agent.'
    )
    autoStart: bool | None = None
    autoDriver: bool | None = None
    idleUnloadSeconds: int | None = None
    startOnDemand: bool | None = None
    flags: dict[str, Any] | None = None
    extraArgs: list[str] | None = None
    env: dict[str, str] | None = None
    workingDirectory: str | None = None
    binary: str | None = None
    driver: str | None = Field(
        None,
        description="Name of the companion `inference-driver` component the agent\ndeclared for this runtime, when `autoDriver` is true. What\nthe gateway's routing table calls this backend, and the\nentry to read in `GET /v1/components` for its health. Absent\nwhen the operator fronts the runtime by hand.\n",
    )
    status: RuntimeStatus
    stopReason: StopReason | None = Field(
        None,
        description='Why a `stopped` runtime is stopped. Present only in that\nstate; cleared on start. An observation, not a declaration\n— it is never replicated, and after a control-root\npromotion the answer is re-read from this agent.\n',
    )
    url: AnyUrl | None = Field(
        None,
        description="Where this engine is actually listening\n(`http://<host>:<port>`). This is the value an\ninference-driver's `baseUrl` points at, and the reason a\ndriver never needs to know about ports or argv.\n",
    )
    argv: list[str] | None = Field(
        None,
        description='The exact command line the agent spawned, as the adapter\nresolved it. Read-only and reported deliberately: the first\nquestion anyone debugging a local engine asks is "what\ncommand did you actually run", and every tool that hides the\nanswer makes that debugging worse. Copy-pasteable.\n',
    )
    pid: int | None = Field(
        None, description='OS process id. Set only while the engine is alive.'
    )
    node: str | None = Field(
        None,
        description='The node this runtime runs on — always *this* agent\'s node,\nsince an agent supervises only its own host.\n\nReported anyway, and this is why: the control root relays\nthese into a union view across every node, and a runtime that\narrived without a node would be a runtime the operator cannot\nlocate. Filled from the agent\'s own identity rather than\ndeclared, so it cannot disagree with reality. Absent on an\nagent that has not enrolled, which is the only state in which\n"which node" has no answer.\n',
    )
    engineVersion: str | None = Field(
        None, description='Version reported by the binary that is actually running.'
    )
    capabilities: RuntimeCapabilities | None = None
    lastRestart: AwareDatetime | None = None
    lastError: str | None = Field(
        None,
        description='Most recent failure for this runtime — a spawn error, a\nnon-zero exit, or a readiness probe that never passed.\nCleared on a successful start.\n',
    )


class StopRequest(BaseModel):
    """
    Optional body for `POST /v1/runtimes/{name}/stop`, saying why.
    Recorded as `Runtime.stopReason` so the dashboard can explain a
    stopped model. Absent means `operator`.

    """

    reason: StopReason | None = None


class Admission(BaseModel):
    """
    Whether a runtime would fit on the device it targets, right now,
    and the arithmetic behind the answer. Returned by
    `POST /v1/runtimes/admission`, and the reasoning behind a 422
    from `POST /v1/runtimes` or `POST /v1/runtimes/{name}/start`.

    Deliberately **not** the library's `Fit`. That schema describes
    a model against a host for the discovery screen; this one
    decides a launch of one spec on one device and names what to do
    about a refusal. They overlap on the verdict words and diverge
    on everything else, and sharing them would couple the discovery
    screen to the supervisor.

    """

    decision: AdmissionDecision
    fit: AdmissionFit
    basis: AdmissionBasis
    requiredBytes: int | None = Field(
        None,
        description='What the launch is estimated to need on the device — weights\nplus KV cache at the requested context plus an overhead\nallowance when the library computed it; file size plus a\nfixed allowance when it did not.\n',
        ge=0,
    )
    freeBytes: int | None = Field(
        None,
        description='Free memory on the largest single target device at the\nmoment of measurement. Free, not total: M3 measured 2.9 GiB\nof a 32 GiB card held on an idle desktop.\n',
        ge=0,
    )
    totalBytes: int | None = Field(None, ge=0)
    device: ComputeDevice | None = Field(
        None, description='The device the verdict is about.'
    )
    contextLength: int | None = Field(
        None,
        description="The context the KV cache was sized for — the spec's\n`contextSize`, or the model's own context when the spec\nleaves it to the engine.\n",
        ge=0,
    )
    blockers: list[AdmissionBlocker] | None = Field(
        None,
        description="Runtimes currently holding memory on that device, most idle\nfirst. What an operator would stop to make room, and the\nlist the gateway's opt-in eviction walks — restricted there\nto runtimes that declared `idleUnloadSeconds`.\n",
    )
    reason: str = Field(
        ...,
        description='The decision in prose, naming the numbers. A refusal that\ndoes not say why is the complaint this endpoint exists to\nanswer.\n',
    )
    warning: str | None = Field(
        None,
        description='Present when the budget could not be fully measured — no\nvendor tool, an unreadable device, a detection path\nunverified on real hardware. An `admit` with a warning is\nan admit on faith, and says so.\n',
    )


class ComponentList(BaseModel):
    components: list[Component] = Field(
        ...,
        description='Components in the order they were configured. The first-run\nwizard fills this in; later editing happens via the\nComponents tab.\n',
    )


class EngineDescriptor(BaseModel):
    """
    One engine adapter, plus what the agent found on this host.

    """

    engine: EngineKind
    available: bool = Field(
        ...,
        description='True iff a usable binary was found and successfully\nversion-probed. When false, `error` says why and runtimes\nfor this engine will fail to spawn.\n',
    )
    modelFormats: list[ModelFormat] = Field(
        ...,
        description="On-disk model formats this adapter's engine can load. A\nproperty of the engine, not of this host — it does not\nchange with `available`.\n\nThis is the engine half of a join the UI performs: the\nlibrary reports what format each model *is*, and this\nreports what each engine can *load*. `llama_cpp` lists\n`gguf`; `vllm` lists `safetensors`. Between them the UI can\ngrey out a launch button and name the missing engine instead\nof offering one that fails.\n\n`vllm` does **not** list `gguf`, though upstream has a path\nfor it. That path is documented as highly experimental and\nunder-optimized, and it needs a second `--tokenizer` model\nbecause converting a GGUF tokenizer is unstable — so\nclaiming the format would light up a launch button across\nthe whole GGUF population llama.cpp already serves properly.\n\nA format match is a *first* filter and not a promise. It says\nthe engine can load this kind of file, not that it can load\nthis model: vLLM's model registry is the authority on\narchitectures and it answers only at spawn. The second\nfilter is therefore the engine's own failure, surfaced\nverbatim through `Runtime.lastError`. No architecture list is\ncopied in here, for the same reason the formats are not\ncopied into the library.\n\nIt lives here because engine knowledge lives here. Putting\nformat support on the library would give the library a copy\nof it, and the copy would be the one that went stale.\n",
    )
    binaryPath: str | None = Field(
        None, description='Absolute path to the binary the adapter would spawn.'
    )
    version: str | None = Field(
        None,
        description="What is running, so an operator can tell what they actually\nhave and so a flag that stopped working after an upgrade is\ndiagnosable. For llama.cpp, the build number as the binary\nreports it.\n\n**Not necessarily obtained by running the engine.** For a\nPython-package engine the version is read from the installed\ndistribution's metadata instead: vLLM exposes it through a\nCLI flag whose module import chain loads PyTorch first, and\npaying that to render a settings panel is not acceptable.\nSame trade the managed store already makes for llama.cpp,\nwhere the recorded build number is returned rather than\nre-probed.\n",
    )
    origin: Origin | None = Field(
        None,
        description="Where the binary came from. Discovery precedence is an\nexplicit `binary` on the runtime, then `configured`, then\n`managed`, then `PATH`.\n\n* `managed` — fetched and verified by us. Only ever set for\n  an engine with `acquisition.policy: managed`.\n* `configured` — an explicit path the operator set. Two\n  sources: a `binary` on one runtime, for someone who builds\n  llama.cpp themselves or wants a specific build for one\n  model; or an install-wide path in the agent's own\n  config, which is how an engine we never manage becomes\n  discoverable at all. Without the second, an operator with\n  a perfectly good vLLM venv would read as unavailable\n  unless they put it on `PATH` or repeated the path on every\n  runtime.\n* `path` — found on `PATH`.\n",
    )
    flagSchema: ConfigSchema | None = Field(
        None,
        description='The **curated** flag surface for this engine, as a standard\n`ConfigSchema` so the generic config editor renders it with\nno engine-specific UI code.\n\nCurated, not complete: `llama-server` has hundreds of flags\nand exposing them wholesale would produce a form nobody can\nuse. What is here is what a person actually turns —\ncontext size, GPU layers, batch size, parallel slots, flash\nattention. Anything omitted is still reachable through\n`RuntimeSpec.extraArgs`.\n',
    )
    error: str | None = Field(None, description='Populated when `available: false`.')
    managed: ManagedEngine | None = None
    acquisition: EngineAcquisition | None = None
    python: PythonEngine | None = Field(
        None,
        description='Present when this engine is a Python package rather than a\nself-contained binary, describing the environment it lives\nin. Absent for llama.cpp.\n',
    )


class RuntimeList(BaseModel):
    runtimes: list[Runtime]


class EngineList(BaseModel):
    engines: list[EngineDescriptor]
