# generated by datamodel-codegen:
#   filename:  control.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, SecretStr


class Os(StrEnum):
    windows = 'windows'
    linux = 'linux'
    macos = 'macos'


class Arch(StrEnum):
    x64 = 'x64'
    arm64 = 'arm64'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str | None = Field(
        None,
        description='Message text. Text-only for now; multimodal extensions\ndeferred. **Nullable, and no longer required:** an assistant\nturn that only calls a tool has no text to carry, and the\nalternative — an empty string — would assert the model said\nnothing when in fact it said something that was not text.\n',
    )
    toolCalls: list[dict[str, Any]] | None = Field(
        None,
        description="On an **assistant** message: the tool calls the model made,\nin OpenAI's `{id, type, function: {name, arguments}}` shape.\n\nDeliberately loose here. This is the *shared* schema, so a\ntightly-typed copy would be a third definition of the same\nobject alongside the gateway's and the driver's, and the one\nplace all three must agree is the wire format, which is\nOpenAI's and not ours to restate. The two API documents\ncarry the strict shapes.\n",
    )
    toolCallId: str | None = Field(
        None,
        description='On a **tool** message: which call this is the result of.\n`content` is the result, serialized by the caller.\n',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the agent's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the agent, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the agent's
    `GET /v1/runtimes`.

    `control` is the trust root, node registry, install-wide
    topology and UI host — exactly one active, plus warm standbys.
    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    **The agent is not in this list**, for the same reason engine
    runtimes are not: it supervises, it is not supervised. Its
    lifecycle belongs to the platform — a systemd unit, a container
    entrypoint — not to a topology entry. `control` *is* in the list
    precisely because the agent on its host supervises it like
    anything else, which is what stops the control root needing a
    second copy of the supervision machinery.

    """

    control = 'control'
    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class ComputeDeviceKind(StrEnum):
    """
    What kind of device this is.

    A named schema rather than an inline enum because an inline one
    generated a bare `Kind` class, which is too generic to sit in a
    module every component imports.

    Note `cpu` is a member, which is why the surrounding schema is
    `ComputeDevice` and not `Accelerator`: a list that includes CPUs
    is a device list. The narrower `HostAccelerator.accelerator` on
    the agent keeps its own name and its own values — it answers
    "which prebuilt engine build fits this machine", not "what can
    this host compute on".

    """

    cuda = 'cuda'
    rocm = 'rocm'
    xpu = 'xpu'
    metal = 'metal'
    cpu = 'cpu'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server` and loads GGUF.
    `vllm` drives upstream `vllm serve` and loads safetensors. MLX
    is a third adapter later. We never ship an engine — every one of
    them is an upstream project we wrap and track.

    The two differ in far more than argv, and that is why readiness
    is per-adapter rather than one shared TCP check:
    `llama-server` answers `/health` while it loads and reports that
    it is loading, whereas vLLM binds its port *before* loading the
    model and refuses connections until the model is in memory — so
    for minutes it is indistinguishable, over the network alone,
    from a process that died. They differ in acquisition too: a
    llama.cpp build is fetched and verified by us, while vLLM is a
    Python package the operator installs themselves. See
    `EngineAcquisition.policy`.

    Lives here rather than on the agent because two components
    reference it: the agent's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'
    vllm = 'vllm'


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08): both are implemented at
    v0.1, and the differences are load-bearing rather than
    cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the agent's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Three of these hold more than a scalar. `path_list` is an
    ordered JSON array of directory paths on the component host —
    the library's model roots are the first and so far only user —
    and the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination.

    `url_list` is the same argument one type over: an ordered JSON
    array of URLs, rendered as an add/remove list of address fields.
    Added at M5 for the control root's standby endpoints, which are
    inherently plural — *"N standbys is a configuration, not a
    mechanism"* — and which have no natural single-value spelling.
    A comma-separated text field would be the same bug report
    `path_list` exists to avoid, and reusing `path_list` for
    addresses would tell every UI to open a directory picker.
    Validation is the field's business rather than the type's; what
    the type promises is a list whose entries are addresses.

    `runtime_name` holds the `name` of a supervised engine runtime,
    and UIs render it as a dropdown sourced from the agent's
    `GET /v1/runtimes`. It exists because `componentKindHint` cannot
    do this job: a runtime is deliberately not a component, so
    `/v1/components` does not list one. What is saved is the
    runtime's *name*, never its URL — the agent assigns the port
    when the operator does not pick one, so a stored URL would
    encode a number the operator never chose and does not own, and
    would be wrong the moment the runtime moved. Its first user is
    the inference-driver's `runtimeName`, which is how a driver
    follows the engine process it fronts.

    `node_name` holds the `name` of an enrolled node, rendered as a
    dropdown sourced from the control root's `GET /v1/nodes`. Same
    reasoning as `runtime_name` one level up: a node is not a
    component either, so `componentKindHint` cannot source it, and
    what is saved is the name rather than a URL because the address
    of a host is topology the control root owns.

    `model_slots` is the gateway's priority-list surface, and the
    one value here that holds objects. An ordered JSON array of
    `{"model": <alias a client asks for>, "targets": [<model id>,
    ...]}`: a request for `model` is served by the drivers serving
    `model` itself, then by the drivers serving each target in
    order, cascading on failure. Targets are **model ids, not driver
    names**, because a model id names a replica set — every driver
    currently serving it, load-balanced — and a driver name would
    name one process. That is why the value reserved since M2 as
    `driver_list` was renamed when M6 defined it: the old name said
    the wrong thing about what goes in the list. A cloud
    subscription is a target like any other, because a
    `claude_code_cli` driver already serves a model id. UIs without
    a structured renderer for it fall back to editing the JSON.

    `path_mappings` (M11) is an ordered JSON array of `PathMapping`
    — `{"from": <a directory as another machine states it>, "to":
    <the same directory on this host>}`. Its one user is the agent's
    `pathMappings`, which is how a node opens model files a library
    on another host described by *its* path: `/models` on the NAS
    is `Z:\\models` here. UIs render it as rows of two directory
    fields, the right-hand one browsable on the component's own
    host, and offer the library's configured roots as suggestions
    for the left. Matching, precedence and translation rules are on
    the agent's field description, not here — the type promises a
    list of pairs and nothing about what they mean.

    `library_folders` (2026-09-14) is an ordered JSON array of
    `LibraryFolder` — `{"path": <a directory on the library's
    host>, "mounts": [<where other machines find the same
    directory>, ...]}`. Its one user is the library's `modelRoots`,
    which was a `path_list` until the reach of a folder moved onto
    the folder: a folder is one exported share, mounted the same
    way on every node of one OS, so the library says where once and
    every node inherits it rather than each node carrying a row per
    folder. A bare string is accepted wherever a `LibraryFolder` is
    expected and means a folder with no mounts — so a config file,
    a PATCH body or a default written for `path_list` still works,
    and `GET /v1/config` always answers in the object form. UIs
    render it as rows of one browsable directory (the library's
    host) plus its mounts; the per-node grid over it is the
    Library's Folders page, not this field.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    url_list = 'url_list'
    duration = 'duration'
    runtime_name = 'runtime_name'
    node_name = 'node_name'
    model_slots = 'model_slots'
    path_mappings = 'path_mappings'
    library_folders = 'library_folders'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the agent handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every agent
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the agent. The passphrase is the same one the operator set
    in the wizard. The agent bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the agent at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the agent's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class PathMapping(BaseModel):
    """
    One rule for reading a path that another machine wrote.

    The library describes each model by its path **on the library's
    own host**, and a runtime declaration copies that string
    verbatim — so when the engine runs elsewhere, the agent there is
    handed a path from a filesystem it does not have. A mapping says
    where the same directory is on this host: the NAS's `/models`
    is `Z:\\models` on the Windows box that mounts it. Nothing is
    copied or cached; the operator mounts the share, and this tells
    the agent where they mounted it.

    Shared here because it appears in two places on the agent: as
    the entries of the `pathMappings` config field, and as
    `ModelLocation.mapping` on an admission answer, which reports
    the rule that applied. Two definitions of one pair would drift.

    """

    from_: str = Field(
        ...,
        alias='from',
        description="A directory as the other machine states it — in practice a\nlibrary root, spelled exactly as the library's own\n`GET /v1/config` lists it. Its shape decides how it matches:\na drive letter or UNC prefix means Windows rules (case-\ninsensitive, `/` and `\\` interchangeable); a leading `/`\nmeans POSIX rules. The agent cannot know the library's\noperating system, and the string came from it, so the\nstring stands in.\n",
    )
    to: str = Field(
        ...,
        description="The same directory on the host holding this config. Used\nverbatim, `~` expanded; the remainder of a matched path is\nre-joined onto it with this host's own separator.\n",
    )


class LibraryFolder(BaseModel):
    """
    One directory the library catalogues, and where other machines
    find it (2026-09-14).

    `path` is the directory as the library's own host spells it —
    what the scanner walks, what a `ModelSummary.path` starts with,
    the left-hand side of every rule that reaches it. `mounts` is
    the same directory as **other** machines see it: a POSIX-shaped
    entry is for Linux and macOS nodes, a Windows-shaped one (drive
    letter or UNC) for Windows nodes, and a node takes the first
    entry of its own shape. That is the whole of "how does node X
    reach folder Y" for every node that mounts the share where the
    folder says; a node that mounts it elsewhere carries one
    override in its agent's `pathMappings`, and a node with no
    mount of its shape opens `path` as written — the identical-mount
    convention, and every single-host install.

    The rule this replaces was per node per folder, on each node's
    agent, and grew as nodes × folders with every row typed by hand.
    This is per folder, stated once. Nothing is copied or cached:
    the operator mounts the share, this says where.

    """

    path: str = Field(
        ...,
        description="Absolute, as the library's host spells it. Immutable in the\nsense that changing it is a different folder: models are\nidentified by their path under it.\n",
    )
    mounts: list[str] | None = Field(
        [],
        description='Absolute paths, each Windows- or POSIX-shaped; the shape\nsays which nodes it is for. Order matters only among entries\nof one shape, where the first wins. Empty means "reached at\n`path`, or not at all".\n',
    )


class DirectoryEntryKind(StrEnum):
    """
    Files appear only when a listing asked for `includeFiles`. A
    directory picker never does; a `file_path` field's picker would,
    which is why the flag exists on the endpoint without a UI yet.

    """

    directory = 'directory'
    file = 'file'


class NodeRole(StrEnum):
    """
    * `control` — the active control root. Exactly one.
    * `standby` — replicating, promotable, serving no writes.
    * `agent` — supervision only, no control-plane state.

    A node's role is *configuration*, not an election outcome.
    Nothing here votes.

    """

    control = 'control'
    standby = 'standby'
    agent = 'agent'


class JoinTokenRequest(BaseModel):
    nodeName: str | None = Field(
        None,
        description='Bind this token to one intended node name. Optional; when\nset, an enrollment presenting a different name is refused,\nwhich turns a leaked token into a token that can only do the\nthing it was minted for.\n',
    )
    ttlSeconds: int | None = Field(
        900,
        description='Short by default. A join token is the one credential that\ngrants membership, and the window in which it is useful is\nthe window in which it is dangerous.\n',
        ge=30,
        le=86400,
    )


class JoinToken(BaseModel):
    token: str = Field(
        ...,
        description='**Shown once.** Not retrievable afterwards and not stored in\nrecoverable form — a lost token is re-minted, never looked\nup.\n',
    )
    expiresAt: AwareDatetime
    nodeName: str | None = Field(
        None, description='The node name this token is bound to, when it is bound.'
    )


class NodeAddressAnnouncement(BaseModel):
    """
    A node telling this root where it now is. Signed by the node, not
    bearer-authenticated — see `PATCH /v1/nodes/{name}`.

    """

    url: AnyUrl = Field(
        ...,
        description="Where other hosts now reach this node's agent. Becomes\n`Node.url`, normalized once on the way into the log exactly\nas enrollment's is.\n",
    )
    sequence: int = Field(
        ...,
        description='Strictly increasing per node, persisted on the node. This\nroot refuses anything at or below `Node.advertiseSequence`,\nwhich is what stops a captured announcement being replayed to\npin a node to an address it has left.\n',
        ge=1,
    )
    signature: str = Field(
        ...,
        description='Detached Ed25519 signature, base64, by the node\'s identity\nsigning key over the **canonical message**: the UTF-8 bytes\nof the JSON object `{"name": "<name>", "sequence":\n<sequence>, "url": "<url>"}` with keys sorted and no\nwhitespace — `json.dumps(obj, sort_keys=True,\nseparators=(",", ":"))`. `name` is the path parameter and\n`url` is the value in this body, verbatim and unnormalized.\n\nSame construction as `RekeyRequest.signature` in\n`agent.yaml`, deliberately: three fields, one serializer,\nstated here so both sides implement it from one sentence.\nIncluding `name` is what stops one node\'s announcement being\nreplayed against another\'s record.\n\n**Verified against the raw request body, never against a\nparsed `url`.** An OpenAPI `format: uri` becomes a URL type\nin most generators, and those normalize — Pydantic\'s\n`AnyUrl` appends a trailing slash to an authority-only URL —\nso a verifier that parses first compares different bytes\nfrom the ones the node signed, and *every* announcement\nfails with what looks like a crypto error. Found by it\nhappening. A signature is over bytes on the wire; `format:\nuri` stays here because the validation and the generated\nclients are still worth having.\n',
    )


class NodeAddressAck(BaseModel):
    name: str
    url: AnyUrl = Field(
        ..., description='The address now recorded, after normalization.'
    )
    sequence: int = Field(..., description='The sequence now recorded.')
    changed: bool = Field(
        ...,
        description='False when the announcement matched what was already\nrecorded, which is the common case on a restart. Nothing was\nappended to the log.\n',
    )


class Enrollment(BaseModel):
    """
    What a newly enrolled node needs in order to participate, and
    nothing more.

    """

    name: str
    epoch: int = Field(
        ...,
        description="The control root's current epoch. The node records it and\nfrom then on refuses any root presenting a lower one.\n",
    )
    signingKey: str = Field(
        ...,
        description="The current service-token signing key, so this node's\ncomponents can verify tokens minted anywhere in the install.\n**This is what a single-watchdog install could not do**: a\ndriver spawned on one host used to reject a gateway's token\nfrom another because the keys were unrelated.\n",
    )
    signingKeyId: str | None = Field(
        None,
        description="The key's generation (`Snapshot.signingKeyId`), so the node\ncan tell a later `POST /v1/node/rekey` that is newer from one\nthat is a replay.\n",
    )
    controlPublicKey: str | None = Field(
        None,
        description="The control root's public key, so the node can verify that\nlater epoch changes come from a root it recognises rather\nthan from anything that can reach its port.\n",
    )
    recoveryPublicKey: str | None = Field(
        None,
        description="The second recipient every secret on this node is sealed to.\nHeld by the control root under the passphrase-derived key, so\na dead node's credentials are recoverable by the operator and\nby nobody else.\n",
    )


class StandbyStatus(BaseModel):
    url: AnyUrl
    appliedIndex: int | None = None
    lagEntries: int | None = Field(
        None,
        description='How many entries behind this standby is. Reported as a count\nof entries rather than a duration, because entries are what\nwould be lost and seconds are not.\n',
        ge=0,
    )
    lastContactAt: AwareDatetime | None = None
    reachable: bool | None = None


class LogOp(StrEnum):
    """
    The complete set of control-state mutations. Closed on purpose:
    **every change goes through one writer and one ordered path**, and
    an operation that is not in this list is an operation that would
    not replicate. Adding a mutation means adding an op here.

    **`updateNode` is the tenth, added at M9**, and it is worth
    saying why the set opened. M5 closed it at nine and the rule that
    closed it was about what does *not* belong: minting a join token
    and initializing the install are not replicated state, so they
    got no op. An address change is the opposite case — it mutates
    `Node.url`, which lives in the snapshot, and by this schema's own
    sentence something that mutates applied state and has no op is
    something that would not replicate. Reusing `enrollNode` as an
    upsert would have worked and been worse: the log is read by
    operators, and a node that moved house would appear to have
    enrolled again.

    """

    enrollNode = 'enrollNode'
    updateNode = 'updateNode'
    revokeNode = 'revokeNode'
    putComponent = 'putComponent'
    deleteComponent = 'deleteComponent'
    putRuntime = 'putRuntime'
    deleteRuntime = 'deleteRuntime'
    patchConfig = 'patchConfig'
    rotateSigningKey = 'rotateSigningKey'
    promote = 'promote'


class PromoteRequest(BaseModel):
    passphrase: SecretStr = Field(
        ...,
        description='Required, and the reason the master key never needs to live\non a standby at rest or cross the wire to it.\n',
    )
    force: bool | None = Field(
        False,
        description='Promote despite trailing the active root. For the operator\nwho has decided that losing the tail beats staying down —\nan explicit choice with a name, not a silent default.\n',
    )


class State(StrEnum):
    """
    `distributing` is the interesting one: nodes that are `down`
    hold a superseded key and are refused until they reconnect
    and are re-keyed. That is why rotation has to be resumable
    and idempotent rather than a single atomic act.

    """

    minting = 'minting'
    distributing = 'distributing'
    done = 'done'
    failed = 'failed'


class Reason(StrEnum):
    operator = 'operator'
    revocation = 'revocation'


class KeyRotation(BaseModel):
    """
    Progress of a service-token signing-key rotation, whether
    triggered explicitly or by revoking a node.

    Phases are named rather than reduced to a percentage because a
    rotation that stops partway leaves the install in a mixed-key
    state, and the operator needs to know which nodes are on which
    key rather than what fraction is done.

    """

    state: State = Field(
        ...,
        description='`distributing` is the interesting one: nodes that are `down`\nhold a superseded key and are refused until they reconnect\nand are re-keyed. That is why rotation has to be resumable\nand idempotent rather than a single atomic act.\n',
    )
    reason: Reason | None = None
    revokedNode: str | None = Field(None, description='Set when `reason: revocation`.')
    nodesTotal: int | None = None
    nodesRekeyed: int | None = None
    nodesPending: list[str] | None = Field(
        None,
        description='Nodes that have not yet taken the new key, named rather than\ncounted, because "which host is stale" is the question an\noperator actually has.\n',
    )
    error: str | None = None
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None


class ComponentPlacement(BaseModel):
    """
    A component, plus which node it runs on. The node dimension is
    the only thing the agent's own view cannot supply.

    """

    node: str
    name: str
    kind: ComponentKind
    url: AnyUrl | None = None
    status: str | None = Field(
        None,
        description="As the owning agent reports it. Deliberately a string here\nrather than a copy of the agent's enum: the agent owns\ncomponent status, and duplicating its enum in this document\nwould create two definitions of one fact.\n",
    )


class RuntimePlacement(BaseModel):
    """
    An engine runtime, plus the node it runs on. Every other field is
    the agent's `Runtime` verbatim, relayed rather than
    reinterpreted — this document adds placement and takes nothing
    away.

    """

    node: str
    name: str
    modelAlias: str | None = Field(
        None,
        description='The model id a client asks the gateway for. Unique across the\n*install*, not just the node — two nodes serving the same\nalias is how replicas are expressed, and the gateway load\nbalances across them.\n',
    )
    status: str | None = None
    url: AnyUrl | None = None
    engine: EngineKind | None = None


class RuntimePlacementSpec(BaseModel):
    """
    A runtime declaration plus where to put it. `spec` is the agent's
    `RuntimeSpec` unchanged; this wrapper adds only the node.

    """

    node: str | None = Field(
        None,
        description='Target host. Omitted means the node the control root runs on,\nso a single-host install never has to name anything.\n',
    )
    spec: dict[str, Any] = Field(
        ...,
        description="The agent's `RuntimeSpec`, forwarded verbatim. Modelled\nloosely here on purpose: the agent's spec is the one\ndefinition of what a runtime declaration is, and restating\nits fields in this document would create a second one that\ndrifts.\n",
    )


class AuthStatus(BaseModel):
    initialized: bool = Field(
        ...,
        description='True once a passphrase has been set. False means every\nendpoint except this one, `/healthz` and\n`POST /v1/auth/initialize` will refuse.\n',
    )


class AuthInitializeRequest(BaseModel):
    passphrase: SecretStr = Field(
        ...,
        description="Hashed with Argon2id and used to derive the master key that\nat-rest secrets are sealed under. Losing it means losing\nevery stored credential — including the recovery recipient\nthat would otherwise reach a dead node's secrets. There is no\nrecovery path, by design.\n",
        min_length=1,
    )


class ComputeDevice(BaseModel):
    """
    One compute device on one host, as that host's agent detected it.

    Shared because it appears on both sides of a join: an agent
    reports its own devices on `GET /v1/node`, and the control root
    aggregates them into `Node.devices` — the cross-host
    inventory M3 deferred with the note that *"building a real
    inventory is topology work"*. Two copies of this shape would be
    two definitions of one fact, and the copy would be the one that
    went stale.

    Deliberately **not** the same thing as the agent's
    `HostAccelerator`, which answers a narrower question — "which
    prebuilt engine build should we fetch for this machine" — and
    describes a host in the singular. This is a device *list*,
    because a host with two cards is the case that makes replicas of
    one model possible.

    """

    kind: ComputeDeviceKind
    name: str | None = Field(
        None,
        description='Device name as the vendor reports it, e.g. `NVIDIA GeForce RTX 5090`.',
    )
    index: int | None = Field(
        None,
        description="Device ordinal on its own host — what `CUDA_VISIBLE_DEVICES`\nor `HIP_VISIBLE_DEVICES` in a runtime's `env` selects to pin\nthat runtime to one card.\n",
        ge=0,
    )
    memoryTotalBytes: int | None = None
    memoryFreeBytes: int | None = Field(
        None,
        description='Free decides whether a model fits, not total — M3 measured\n2.9 GiB of a 32 GiB card already held on an idle desktop.\nBoth are reported so the difference is visible rather than\nsurprising.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the agent's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class DirectoryEntry(BaseModel):
    name: str
    path: str = Field(
        ..., description='Absolute path, ready to be used as a config value.'
    )
    kind: DirectoryEntryKind
    hidden: bool | None = Field(
        False,
        description='A dot-prefixed name, or the hidden attribute on Windows.\nOnly present in a listing that asked for `showHidden`.\n',
    )


class EnrollmentRequest(BaseModel):
    token: str = Field(
        ..., description="The join token, which is this request's only credential."
    )
    name: str = Field(..., min_length=1)
    publicKey: str = Field(
        ...,
        description="The agent's identity public key. The private half stays on\nthe node; sending it would defeat the point of per-node\nsealing.\n",
    )
    signingPublicKey: str | None = Field(
        None,
        description="The agent's Ed25519 public key, recorded as\n`Node.signingPublicKey` and used to verify later address\nannouncements. Optional so an older agent still enrolls; the\ncost of omitting it is that the node cannot re-advertise.\n",
    )
    url: AnyUrl | None = Field(
        None,
        description="Where other hosts reach this agent — its `advertiseUrl`,\nconfigured or derived (`agent.yaml`, `GET /v1/node`). Becomes\n`Node.url`. The agent sends it because the agent knows which\ninterface it used to reach this root; a root deriving it from\nthe request's source address would be right on a flat mesh\nnetwork and wrong behind anything else.\n",
    )
    agentVersion: str | None = None
    os: Os | None = None
    arch: Arch | None = None
    devices: list[ComputeDevice] | None = None


class ControlStatus(BaseModel):
    role: NodeRole
    epoch: int = Field(
        ...,
        description='Monotonic generation of the control root. Incremented by\npromotion, and the whole of the fencing mechanism: agents\nrefuse a lower epoch, so a superseded root cannot command\nanything that has already heard from its successor.\n',
        ge=1,
    )
    appliedIndex: int = Field(
        ..., description='The highest log index this process has applied.', ge=0
    )
    firstAvailableIndex: int | None = Field(
        None,
        description='Oldest index still in the log after compaction. A standby\nwhose position predates this cannot catch up by reading the\nlog and must take a snapshot instead.\n',
    )
    standbys: list[StandbyStatus] | None = Field(
        None,
        description='Present on the active root. **This is the "is failover safe\nright now" answer** — a standby trailing the active root\ncannot be promoted without losing the difference, and an\noperator should see that before a failure rather than during\none.\n',
    )
    activeUrl: AnyUrl | None = Field(
        None, description='Where the active root is, as reported by a standby.'
    )
    initialized: bool | None = None


class LogEntry(BaseModel):
    """
    One control-state change. Applied state is a deterministic
    function of the entries applied so far, which is the property
    that makes a standby's state comparable to the active root's —
    and the property a later move to consensus would depend on.

    """

    index: int = Field(
        ...,
        description='Gapless and monotonic, assigned by the active root alone.\n**The only ordering there is.**\n',
        ge=1,
    )
    epoch: int = Field(
        ...,
        description='The control-root generation that appended this entry. A\nstandby rejects entries from an epoch below the highest it\nhas seen, which fences a superseded root out of the log as\nwell as out of the agents.\n',
    )
    op: LogOp
    payload: dict[str, Any] | None = Field(
        None, description='Operation-specific. Shape follows `op`.'
    )
    at: AwareDatetime | None = Field(
        None,
        description='**Informational only, never used for ordering.** Recorded so\nan operator can read the log; deliberately not load-bearing,\nwhich is what keeps clock skew between buildings out of the\ncorrectness argument.\n',
    )


class ComponentPlacementList(BaseModel):
    components: list[ComponentPlacement]
    unreachableNodes: list[str] | None = Field(
        None,
        description='Nodes that could not be asked. Named explicitly so the view\nis honestly partial rather than quietly short.\n',
    )


class RuntimePlacementList(BaseModel):
    runtimes: list[RuntimePlacement]
    unreachableNodes: list[str] | None = Field(
        None,
        description='Nodes that could not be asked. A dashboard showing fewer\nruntimes than exist, with no indication why, is worse than\none that names the host it could not reach.\n',
    )


class Node(BaseModel):
    """
    One host in this install.

    Identified by an operator-supplied `name`, consistent with
    components and runtimes — but its *identity* is `publicKey`. A
    name is a label an operator can read; the keypair is what makes
    a node the same node after a restart, and what a secret is sealed
    to.

    """

    name: str = Field(
        ...,
        description='Operator-supplied, unique per install. Used in\n`Runtime.node`, `RuntimePlacementSpec.node`, and anywhere a\nplacement has to be named.\n',
        min_length=1,
    )
    url: AnyUrl | None = Field(
        None,
        description="Where this node's agent is reachable — from this root, and from\na gateway sending a lifecycle action to the agent that owns a\nruntime. Recorded verbatim from `EnrollmentRequest.url`; the\nagent is the one that knows how it reached this root, and this\nroot does not guess from a source address.\n",
    )
    role: NodeRole
    reachable: bool = Field(
        ...,
        description="Whether the control root could reach this node's agent on its\nlast attempt. False means `down`, not `out` — see this\ndocument's description. Nothing is reassigned on the strength\nof this field alone.\n",
    )
    publicKey: str | None = Field(
        None,
        description="The node's identity public key, generated at enrollment. The\nprivate half never leaves the node, which is what makes\nper-node sealing meaningful: a secret sealed to this key can\nbe read by this host and by the recovery recipient, and by\nnothing else.\n",
    )
    signingPublicKey: str | None = Field(
        None,
        description="The node's **Ed25519** public key, used for one thing: to\nverify that a `PATCH /v1/nodes/{name}` really came from this\nnode. `publicKey` cannot do it — that one is X25519 and\nexists so secrets can be sealed to the node — and a key that\nboth seals and signs is a key whose compromise costs twice.\n\nAbsent on a node enrolled before nodes had a signing\nidentity. Such a node cannot re-advertise and must re-enroll;\nsurfaced here rather than inferred from a 401.\n",
    )
    advertiseSequence: int | None = Field(
        None,
        description='The highest announcement sequence accepted from this node. A\n`PATCH /v1/nodes/{name}` at or below it is a replay and is\nrefused. Applied state, so a promoted standby refuses the\nsame replays this root would.\n',
        ge=0,
    )
    lastSeenEpoch: int | None = Field(
        None,
        description='The highest control-root epoch this node has acknowledged. A\nvalue below `ControlStatus.epoch` is the visible symptom of a\nnode that was partitioned during a promotion — bounded,\nself-healing, and deliberately surfaced rather than hidden.\n',
        ge=0,
    )
    agentVersion: str | None = None
    os: Os | None = None
    arch: Arch | None = None
    devices: list[ComputeDevice] | None = Field(
        None,
        description='What this host can compute on. **This is the cross-host\nhardware inventory M3 deferred**, and it lands here exactly\nas M3 predicted: *"building a real inventory is topology work\nand belongs to the agent if it belongs anywhere."*\n\nThe library\'s fit surface already takes a hardware override\nand reports which host it measured, so multi-host quant\nguidance works as soon as these exist. Reported, not acted\non — deciding *which* node should host a model is lifecycle\npolicy, which is M6.\n',
    )
    enrolledAt: AwareDatetime | None = None
    lastSeenAt: AwareDatetime | None = None
    lastError: str | None = Field(
        None,
        description='Why the last probe of this node did not come back with an\nidentity, in the probe client\'s words -- an HTTP status and\nthe body\'s title, or a transport error. `null` when the node\nanswered, and when nothing has polled yet.\n\nAdded 2026-09-15 because `reachable: false` on its own sent an\noperator looking at enrollment, keys and firewalls when the\ncause was a worker refusing this root\'s tokens as "not yet\nvalid (iat)" over half a second of clock skew. The probe\nclient had the reason the whole time; this surface dropped\nit. Observation, not applied state: a standby has not seen\nwhat this root saw, so it is never replicated.\n',
    )


class DirectoryListing(BaseModel):
    """
    One directory on the component's own host, listed for a picker.

    Returned by `GET /v1/directories` on the library (whose host
    holds the model roots) and on the agent (whose host holds a
    path mapping's `to`, and any engine binary an operator points
    at). The same shape on both, because the UI has one picker and
    the only thing that differs is which machine's disk it is
    looking at — which is why `host` is on the response.

    This is the endpoint behind the promise `path_list` has carried
    since M2: *"an add/remove list of directory pickers"*. It lists
    what an operator could already type into a path field, on
    request, to the strongest credential there is; it is not a new
    capability and it is not a file browser.

    """

    host: str = Field(
        ...,
        description='The machine whose disk this is. On a multi-host install the\nanswer to "browse" is frequently a machine other than the\none the browser is on.\n',
    )
    path: str | None = Field(
        None,
        description='The directory listed, absolute and as this host spells it.\nAbsent when no `path` was asked for, in which case `entries`\nare the places to start from — every drive on Windows, `/`\non POSIX, and the home directory.\n',
    )
    parent: str | None = Field(
        None,
        description='The directory above `path`, so a picker can go up without\ndoing path arithmetic in a browser. Absent at a filesystem\nroot and when `path` is absent.\n',
    )
    entries: list[DirectoryEntry] = Field(
        ...,
        description='Sorted by name, directories first. Entries this component\nmay not read are omitted rather than failing the listing.\n',
    )


class LogPage(BaseModel):
    entries: list[LogEntry] = Field(
        ..., description='Oldest first, gapless, strictly increasing `index`.'
    )
    appliedIndex: int = Field(
        ...,
        description="The active root's own applied index, so a caller can compute its lag.",
    )
    firstAvailableIndex: int | None = Field(
        None,
        description='Reported on every page so a standby learns it has fallen\nbehind compaction *before* it tries to read a gap.\n',
    )


class Snapshot(BaseModel):
    """
    Applied state as of `index`, for bootstrapping a standby or
    recovering one that fell behind compaction.

    Carries the replication set and nothing else. The passphrase
    exists only in the operator's head; per-component secrets are
    sealed on the hosts that read them and never travel here.

    **The governing rule, learned by implementing it:** a snapshot
    has to be able to reproduce exactly what the log produces,
    because it *is* the log's compacted head. **Every** `LogOp` value
    must have somewhere to land here, or compaction
    silently discards the state that op wrote — and the loss shows
    up at a promotion rather than at the compaction. Adding an op
    means checking this schema can hold its effect.

    **`Node.reachable` in a snapshot is not an observation.** It is
    required by that schema and a snapshot carries no observations,
    so it is always `false` here and a reader must not treat it as a
    report about the host. Reachability, `lastSeenAt` and
    `lastSeenEpoch` belong to whichever root did the polling; see
    `GET /v1/nodes`.

    """

    index: int
    epoch: int
    nodes: list[Node] | None = None
    components: list[ComponentPlacement] | None = None
    runtimes: list[RuntimePlacementSpec] | None = Field(
        None,
        description='Runtime **declarations** — what should be running where —\nand deliberately not `RuntimePlacement`, which is the\nreporting shape and carries no `spec`.\n\n§4 of the design requires "declared runtimes" to survive,\nand a placement without its spec is not a declaration: a\npromoted standby holding one would know a runtime\'s name and\nnothing about the model path or flags it launches with.\n`node` is always present here even though the schema allows\nit to be omitted elsewhere; a snapshot has no "the node the\ncontrol root runs on" default to fall back on, because the\nroot that reads it may not be the root that wrote it.\n',
    )
    config: dict[str, Any] | None = Field(
        None,
        description="The control root's own applied configuration.\n\nReplicated because `patchConfig` is one of the ops, so\nconfig *is* control state — and a snapshot that dropped it\nwould lose every config change made before the last\ncompaction. A promoted standby that came up without\n`standbyUrls` would silently have no standbys of its own,\nwhich is the failure mode where the second failover is the\none that hurts.\n",
    )
    signingKeyId: str | None = Field(
        None,
        description='Names the current signing-key generation. Not a secret, and\nthe thing a node reports back so a rotation can tell which\nhosts are stale rather than counting how many are.\n',
    )
    salt: str | None = Field(
        None,
        description='The Argon2id salt. Replicated because without it the same\npassphrase derives a different key, and a standby that cannot\nderive the master key cannot be promoted.\n',
    )
    passphraseVerifier: str | None = Field(
        None,
        description='Lets a standby authenticate the operator at promotion without\nholding the master key.\n',
    )
    sealedRecoveryKey: str | None = Field(
        None,
        description="The recovery recipient, sealed under the passphrase-derived\nkey. Replicated so a promoted standby can still reach a dead\nnode's secrets; useless to anyone without the passphrase.\n",
    )
    sealedSigningKey: str | None = Field(
        None,
        description='The current service-token signing key, sealed under the\npassphrase-derived key.\n\nThe design\'s replication set requires this — *"otherwise\nevery node must re-enroll after promotion"* — and the first\nimplementation found it missing here, which would have made\na snapshot-bootstrapped standby unpromotable without\nre-enrolling the install. It is **sealed** rather than\nplaintext because a snapshot is a file on a second host and\nthis key mints every service token in the install; the\nstandby has the salt and the verifier but no master key\nuntil the operator supplies the passphrase at promotion,\nwhich is exactly the moment it needs to open this.\n',
    )
    sealedControlKey: str | None = Field(
        None,
        description="The control root's own identity private key, sealed under\nthe passphrase-derived key. Its public half is what nodes\nrecord at enrollment as `controlPublicKey` and check epoch\nchanges against, so a promoted standby that generated a\n*fresh* identity would be rejected by every enrolled node.\nReplicating it is what makes promotion a change of host\nrather than a change of identity.\n",
    )
    controlPublicKey: str | None = Field(
        None,
        description='The public half of the above, carried in the clear so a\nstandby can report the identity it would assume without\nholding the passphrase.\n',
    )


class NodeList(BaseModel):
    nodes: list[Node]
